# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"\x07\n\x05\x45mpty\"\x18\n\x08TermName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x04Link\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"9\n\nDefinition\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1d\n\x05links\x18\x02 \x03(\x0b\x32\x0e.glossary.Link\"E\n\x08Relation\x12\x11\n\tfrom_term\x18\x01 \x01(\t\x12\x0f\n\x07to_term\x18\x02 \x01(\t\x12\x15\n\rrelation_type\x18\x03 \x01(\t\"e\n\x04Term\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\ndefinition\x18\x02 \x01(\x0b\x32\x14.glossary.Definition\x12%\n\trelations\x18\x03 \x03(\x0b\x32\x12.glossary.Relation\"*\n\tTermsList\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term\"9\n\x05Graph\x12\r\n\x05nodes\x18\x01 \x03(\t\x12!\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x12.glossary.Relation\"3\n\x0fOperationStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd5\x02\n\x0fGlossaryService\x12\x33\n\x0bGetAllTerms\x12\x0f.glossary.Empty\x1a\x13.glossary.TermsList\x12\x33\n\rGetTermByName\x12\x12.glossary.TermName\x1a\x0e.glossary.Term\x12,\n\x08GetGraph\x12\x0f.glossary.Empty\x1a\x0f.glossary.Graph\x12\x34\n\x07\x41\x64\x64Term\x12\x0e.glossary.Term\x1a\x19.glossary.OperationStatus\x12\x37\n\nUpdateTerm\x12\x0e.glossary.Term\x1a\x19.glossary.OperationStatus\x12;\n\nDeleteTerm\x12\x12.glossary.TermName\x1a\x19.glossary.OperationStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_TERMNAME']._serialized_start=37
  _globals['_TERMNAME']._serialized_end=61
  _globals['_LINK']._serialized_start=63
  _globals['_LINK']._serialized_end=97
  _globals['_DEFINITION']._serialized_start=99
  _globals['_DEFINITION']._serialized_end=156
  _globals['_RELATION']._serialized_start=158
  _globals['_RELATION']._serialized_end=227
  _globals['_TERM']._serialized_start=229
  _globals['_TERM']._serialized_end=330
  _globals['_TERMSLIST']._serialized_start=332
  _globals['_TERMSLIST']._serialized_end=374
  _globals['_GRAPH']._serialized_start=376
  _globals['_GRAPH']._serialized_end=433
  _globals['_OPERATIONSTATUS']._serialized_start=435
  _globals['_OPERATIONSTATUS']._serialized_end=486
  _globals['_GLOSSARYSERVICE']._serialized_start=489
  _globals['_GLOSSARYSERVICE']._serialized_end=830
# @@protoc_insertion_point(module_scope)
